name: Add Website Issue Report to Website Management Project Board

on:
  issues:
    types: [opened]

jobs:
  add_to_project:
    runs-on: ubuntu-latest

    steps:
      - name: Add website and triage labels
        uses: actions-ecosystem/action-add-labels@v1
        with:
          github_token: ${{ secrets.WEBSITE_MGMT_PERSONAL_ACCESS_TOKEN }}
          labels: |
            website
            triage

      - name: Add reported website issue to Website Management Project Board
        if: contains(join(github.event.issue.labels.*.name), 'website') && contains(join(github.event.issue.labels.*.name), 'triage')
        uses: actions/add-to-project@v1.0.1
        with:
          project-url: https://github.com/orgs/thewpcommunitycollective/projects/6
          github-token: ${{ secrets.WEBSITE_MGMT_PERSONAL_ACCESS_TOKEN }}
          status: "To Do"
          labeled: website, triage
          label-operator: AND
